Fixed package data config to make template alive
xonsh/xontrib-cookiecutter pull request #2
Opened 2020-10-06 10:23 UTC by anki-code

Hi! 
Thank you for this template!
But it is not working. This PR makes it working.

2020-10-07 17:33 UTC, anki-code commented
@scopatz or @AstraLuma please merge.

2020-10-07 20:20 UTC, scopatz commented
CC @xonsh/xore - I don't really know cookiecutter well enough to evaluate

2020-10-07 20:21 UTC, anki-code commented
@scopatz I've tested it 5 times to write a readme. Merge without worries :)

2020-10-07 20:34 UTC, scopatz commented
Sorry, I think a real review is needed.  We try not to merge blindly :wink:

2020-10-07 20:39 UTC, anki-code commented
Okay, 5 months it was broken, couple of weeks not a problem. 

But you can just 5 minute test if you don't trust me:
```
pip install cookiecutter
cookiecutter gh:anki-code/xontrib-cookiecutter
# enter snail to all lines
pip install -U xontrib-snail
xontrib load snail
# This is snail!
```

2020-10-07 20:44 UTC, scopatz commented
Yeah, I really appreciate all of your effort here!

2020-10-09 08:39 UTC, anki-code commented
@AstraLuma Jamie, please take a look. 
I'm going to add the info about this template to all of my xontribs that have 8+ stars.

2020-10-14 14:42 UTC, AstraLuma requested changes

2020-10-14 14:42 UTC, AstraLuma commented on README.md
> +* `.gitignore` file with standart list of directories to ignore
```suggestion
* `.gitignore` file with standard list of directories to ignore
```

2020-10-16 09:01 UTC, anki-code commented
@AstraLuma I fixed your proposal almost immediately. May be the notification missing. Please review.

2020-10-16 14:24 UTC, gforsyth commented
@anki-code -- a lot of us have 100s, if not 1000s of github notifications, so we tend to turn off commit-level notifications.  Always good to ping us on an issue after pushing up a commit.

2020-10-16 14:30 UTC, gforsyth requested changes
Thanks for putting this together @anki-code!  I think we can remove Python 3.5, and I've tweaked some of the language a little bit.

2020-10-16 14:30 UTC, gforsyth commented on xontrib-{{cookiecutter.project_slug}}/setup.py
> +    python_requires='>=3.5',
```suggestion
    python_requires='>=3.6',
```

2020-10-16 14:30 UTC, gforsyth commented on xontrib-{{cookiecutter.project_slug}}/setup.py
> +        "Programming Language :: Python :: 3.5",
```suggestion
```

2020-10-16 14:30 UTC, gforsyth commented on xontrib-{{cookiecutter.project_slug}}/xontrib/{{cookiecutter.project_slug}}.xsh
> +# Good strart! Get more documentation -> https://xon.sh/contents.html#guides
```suggestion
# Good start! Get more documentation -> https://xon.sh/contents.html#guides
```

2020-10-16 14:30 UTC, gforsyth commented on xontrib-{{cookiecutter.project_slug}}/README.md
> +**Add topics to the repository**. To show the xontrib repository in Github Topics please add topics `xonsh` and `xontrib` to the repository "About" setting. Also add thematic topics for example `ssh`
```suggestion
**Add topics to the repository**. To show the xontrib repository in Github Topics please add topics `xonsh` and `xontrib` to the repository "About" setting. Also add thematic topics, for example,  `ssh` if your xontrib helps work with `ssh`.
```

2020-10-16 14:30 UTC, gforsyth commented on xontrib-{{cookiecutter.project_slug}}/README.md
> +**Repository name**. It's a good practice to add `xontrib-` prefix before the name of your repository. It allows use the Github search to find it.
```suggestion
**Repository name**. It's a good practice to add `xontrib-` prefix before the name of your repository. It helps Github search find it.
```

2020-10-16 14:30 UTC, gforsyth commented on xontrib-{{cookiecutter.project_slug}}/README.md
> +After you create the xontrib repository you can do some helpful tasks to spread the words about xontrib.
```suggestion
After you create the xontrib repository you can do some helpful tasks to spread the word about your xontrib.
```

2020-10-16 14:30 UTC, gforsyth commented on README.md
> +To create xontrib from the template just run:
```suggestion
To create a `xontrib` from this template just run:
```

2020-10-16 15:10 UTC, anki-code commented
@gforsyth many thank! All changes are merged.

> Always good to ping us on an issue after pushing up a commit.

Got it! Ready to merge.

2020-10-16 16:03 UTC, gforsyth approved these changes
Ok, this looks good to me.  Thanks @anki-code !

2020-10-16 16:04 UTC, merged